# Generated by Django 5.0.3 on 2024-04-09 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_rename_doctor_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.IntegerField(max_length=10, validators=[django.core.validators.MinLengthValidator(10, message='Mobile number must be exactly 10 digits'), django.core.validators.MaxLengthValidator(10, message='Mobile number must be exactly 10 digits')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
