# Generated by Django 5.0.3 on 2024-04-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_appointment_date_alter_appointment_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='mobile',
        ),
    ]
